//
//  HomeInteractor.swift
//  titikA
//
//  Created by Afriyandi Setiawan on 21/04/20.
//  Copyright (c) 2020 phe@work. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class HomeInteractor {
}

// MARK: - Extensions -

extension HomeInteractor: HomeInteractorInterface {
    func fetch(data: @escaping ([BaseModel]?) -> Void) {
        APICaller(urlPath: "/api/herostats")
            .fetch(model: [BaseModel.self]) { (result) in
                switch result {
                case .success(let message):
                    data(message)
                case .failure(let err):
                    data(nil)
                    debugPrint(err)
                }
        }
    }
}
