//
//  HomePresenter.swift
//  titikA
//
//  Created by Afriyandi Setiawan on 21/04/20.
//  Copyright (c) 2020 phe@work. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class HomePresenter {
    
    // MARK: - Private properties -
    
    private unowned let view: HomeViewInterface
    private let formatter: HomeFormatterInterface
    private let interactor: HomeInteractorInterface
    private let wireframe: HomeWireframeInterface
    private var dataTable: [String]?
    private var dataModel: [BaseModel]?
    
    // MARK: - Lifecycle -
    
    init(view: HomeViewInterface, formatter: HomeFormatterInterface, interactor: HomeInteractorInterface, wireframe: HomeWireframeInterface) {
        self.view = view
        self.formatter = formatter
        self.interactor = interactor
        self.wireframe = wireframe
    }
    
    func viewDidLoad() {
        view.set(title: "Dota Heroes")
        interactor.fetch { (model) in
            guard let model = model else {
                return
            }
            self.dataModel = model
            self.dataTable = self.formatter.formatFor(type: .table, data: model)
        }
        view.tableView.registerCell(HomeTableViewCell.self)
    }
}

// MARK: - Extensions -

extension HomePresenter: HomePresenterInterface {
    
    func populateHeroes(index: Int) -> [BaseModel] {
        return self.formatter.formatFor(type: .hero(role: self.dataTable?[index] ?? ""), data: self.dataModel ?? []) ?? []
    }
    
    func numberOfRowsIn(section: Int) -> Int {
        return self.dataTable?.count ?? 0
    }
    
    func cellForRowAt(index: IndexPath) -> UITableViewCell {
        return view.tableView.dequeueCell(HomeTableViewCell.self, indexPath: index).setup(text: self.dataTable?[index.row] ?? "TBD")
    }
    
    func didSelectRowAt(index: IndexPath) {
        wireframe.gotoHeroList(query: self.dataTable?[index.row] ?? "TBD", data: populateHeroes(index: index.row))
    }
    
}
