//
//  HomeWireframe.swift
//  titikA
//
//  Created by Afriyandi Setiawan on 21/04/20.
//  Copyright (c) 2020 phe@work. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum HomeRoutes {
    case heroes(query: String, data: [BaseModel])
}

final class HomeWireframe: BaseWireframe {

    // MARK: - Module setup -

    init() {
        let moduleViewController = HomeViewController()
        super.init(viewController: moduleViewController)
        
        let formatter = HomeFormatter()
        let interactor = HomeInteractor()
        let presenter = HomePresenter(view: moduleViewController, formatter: formatter, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }
    
    private func navigate(to: HomeRoutes) {
        switch to {
        case .heroes(let query, let data):
            viewController.showDetailViewController(HeroesWireframe(query: query, heroes: data).viewController, sender: nil)
        }
    }
}

// MARK: - Extensions -

extension HomeWireframe: HomeWireframeInterface {
    func gotoHeroList(query: String, data: [BaseModel]) {
        self.navigate(to: .heroes(query: query, data: data))
    }
}
