//
//  HomeInterfaces.swift
//  titikA
//
//  Created by Afriyandi Setiawan on 21/04/20.
//  Copyright (c) 2020 phe@work. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol HomeWireframeInterface: WireframeInterface {
    func gotoHeroList(query: String, data: [BaseModel])
}

protocol HomeViewInterface: ViewInterface {
    var tableView: UITableView! { get }
}

protocol HomePresenterInterface: PresenterInterface {
    func populateHeroes(index: Int) -> [BaseModel]
    func numberOfRowsIn(section: Int) -> Int
    func cellForRowAt(index: IndexPath) -> UITableViewCell
    func didSelectRowAt(index: IndexPath)
}

protocol HomeFormatterInterface: FormatterInterface {
    func formatFor<T,R>(type: FormatterFor, data: T) -> [R]?
}

protocol HomeInteractorInterface: InteractorInterface {
    func fetch(data: @escaping ([BaseModel]?) -> Void)
}
