//
//  HeroesPresenter.swift
//  titikA
//
//  Created by Afriyandi Setiawan on 03/05/20.
//  Copyright (c) 2020 phe@work. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class HeroesPresenter {

    // MARK: - Private properties -

    private unowned let view: HeroesViewInterface
    private let wireframe: HeroesWireframeInterface
    private var data: [BaseModel]?
    private var query: String?

    // MARK: - Lifecycle -

    init(view: HeroesViewInterface, wireframe: HeroesWireframeInterface) {
        self.view = view
        self.wireframe = wireframe
        self.data = nil
    }
    
    internal init(view: HeroesViewInterface, wireframe: HeroesWireframeInterface, query: String, data: [BaseModel]) {
        self.view = view
        self.wireframe = wireframe
        self.query = query
        self.data = data
    }
    
    func viewDidLoad() {
        view.set(title: query ?? "TBD")
        view.collectionView.collectionViewLayout = SimpleLayout()
        view.collectionView.registerCell(HeroesCollectionViewCell.self)
    }
}

// MARK: - Extensions -

extension HeroesPresenter: HeroesPresenterInterface {
    func update(with data: [BaseModel]) {
        self.data = data
    }
    
    func numberOfItemsIn(section: Int) -> Int {
        return data?.count ?? 0
    }
    
    func cellForRowAt(index: IndexPath) -> UICollectionViewCell {
        return view.collectionView.dequeueCell(HeroesCollectionViewCell.self, indexPath: index).setup(data: data?[index.row])
    }
    
    func didSelectRowAt(index: IndexPath) {
    }
}
