//
//  HeroesWireframe.swift
//  titikA
//
//  Created by Afriyandi Setiawan on 03/05/20.
//  Copyright (c) 2020 phe@work. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class HeroesWireframe: BaseWireframe {

    // MARK: - Module setup -

    init() {
        let moduleViewController = HeroesViewController()
        super.init(viewController: moduleViewController)
        
        let presenter = HeroesPresenter(view: moduleViewController, wireframe: self)
        moduleViewController.presenter = presenter
    }
    
    internal init(query: String, heroes: [BaseModel]) {
        let moduleViewController = HeroesViewController()
        super.init(viewController: moduleViewController)
        
        let presenter = HeroesPresenter(view: moduleViewController, wireframe: self, query: query, data: heroes)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension HeroesWireframe: HeroesWireframeInterface {
}
