//
//  HeroDetailViewController.swift
//  titikA
//
//  Created by Afriyandi Setiawan on 03/05/20.
//  Copyright (c) 2020 phe@work. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class HeroDetailViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: HeroDetailPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
    }
	
}

// MARK: - Extensions -

extension HeroDetailViewController: HeroDetailViewInterface {
}
