//
//  HeroDetailInterfaces.swift
//  titikA
//
//  Created by Afriyandi Setiawan on 03/05/20.
//  Copyright (c) 2020 phe@work. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol HeroDetailWireframeInterface: WireframeInterface {
}

protocol HeroDetailViewInterface: ViewInterface {
}

protocol HeroDetailPresenterInterface: PresenterInterface {
}
