//
//  HeroDetailPresenter.swift
//  titikA
//
//  Created by Afriyandi Setiawan on 03/05/20.
//  Copyright (c) 2020 phe@work. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class HeroDetailPresenter {

    // MARK: - Private properties -

    private unowned let view: HeroDetailViewInterface
    private let wireframe: HeroDetailWireframeInterface

    // MARK: - Lifecycle -

    init(view: HeroDetailViewInterface, wireframe: HeroDetailWireframeInterface) {
        self.view = view
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension HeroDetailPresenter: HeroDetailPresenterInterface {
}
